apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: team-academia
spec:
  selector:
    matchLabels:
      app: front
  replicas: 2
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: team-academia
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80 