services: 
  vote:
    image: AJGH/vote-app:vote
    build:
      context: ./vote
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./vote:/usr/local/app
    ports:
      - 8080:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
  redis: 
    image: redis:alpine
    volumes:
      - ./healthchecks:/healthchecks
  result:
    build: 
      context: ./result
      dockerfile: Dockerfile
    volumes:
      - ./resilt:/usr/local/app
    ports:
      - 8081:80
      