services:
  vote:
    image: jackmurillo/vote-app:vote
    build: 
      context: ./vote
      dockerfile: Dockerfile
      target: dev
    volumes: 
      - ./vote:/usr/local/app
    ports:
      - 8080:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      redis:
        condition: service_healthy
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  redis:
    image: redis:alpine
    volumes: 
      - ./healthchecks:/healthchecks
  result:
    build:
      context: ./result
      dockerfile: Dockerfile
    volumes: 
      - ./result:/usr/local/app
    ports:
      - 8081:80 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
  db:
    image: jackmurillo/vote-app:db
    build: 
      context: ./bd
      dockerfile: Dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
volumes:
      db-data: