apiVersion: v1
kind: Pod
metadata:
  name: test-secret
  namespace: team-academia
  labels:
    name: test
spec:
  containers:
  - name: test-secret
    image: ubuntu
    command: ["/bin/sh", "-c", "sleep 100000000"]
    envFrom:
    - secretRef:
        name: test-secret
  restartPolicy: Never