apiVersion: v1
kind: Pod
metadata:
  name: test-container
  namespace: team-academia
  labels:
    name: test
spec:
  containers:
  - name: test-container
    image: ubuntu
    env:
    - name: SLEEP_TIME
      value: "100000000"
    - name: datos
      valueFrom:
        secretKeyRef:
          name: datos
          key: datos.txt
    command: ["/bin/sh", "-c", "sleep $SLEEP_TIME"]
  restartPolicy: Never
