apiVersion: v1
kind: Pod
metadata:
  name: test-container
  namespace: team-academia
  labels:
    name: test
spec:
  containers:
  - name: test-container
    image: ubuntu
    command: ["/bin/sh", "-c", "sleep 100000000"]
    env: 
    - name: datos
      valueFrom:
        secretKeyRef:
          name: datos
          key: datos.txt
  restartPolicy: Never