apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  containers:
  - name: tomcat
    image: tomcat
  restartPolicy: Always
  resrestartPolicy: Onfailure
  # restartPolicy: Never
 