apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  labels: 
    type: back
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30543
    protocol: TCP
  selector:
    name: academia-apache