services:
  jenkins:
    networks:
      - jenkins   
    image: jenkins/jenkins:2.492.2-jdk17
    ports:
      - 8081:8080 # Cambia el puerto local a 8081
      - 50000:50000
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./jenkins-cert:/certs/client:ro

volumes: 
  jenkins-data:
  jenkins-cert:

networks:
  jenkins:
    driver: bridge