apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-mem
  namespace: team-academia
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "350Mi"
            cpu: "500m"
          requests:
            memory: "125Mi"
            cpu: "250m"
        ports:
        - containerPort: 80