apiVersion: v1
kind: Pod
metadata:
  name: multi
  labels:
    app: multi
spec:
  containers:
  - name: web
    image: ngnix:latest
    ports:
      - containerPort: 80
  - name: frontal
    image: alpine
    command: ["watch", "-m5", "ping", "localhost"]
    # otro comando es
    # command: ["/bin/sh", "-c", "echo 'hello world'"]