apiVersion: v1
kind: Pod
metadata:
  name: apache
  namespace: team-academia
  labels:
    name: apache
spec:
  containers:
  - name: apache
    image: httpd:latest
    ennFrom: ## carar desde el ambiente
      - cconfigMapRef: 
        name: apache