# Usa una imagen base de Python 3.9 o superior
FROM python:3.9

# Configura el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos necesarios para la aplicación
COPY requirements.txt requirements.txt
COPY app.py app.py

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto 8080
EXPOSE 8080

# Ejecuta la aplicación Flask
CMD ["python", "app.py"]
